/*
Banco de Dados criado por:
-Plynio Henrique Murat da Silva
-Rafael Correa de Melo
*/

CREATE DATABASE TRABALHO
USE TRABALHO

DROP TABLE TR_INSTRUMENTO
DROP TABLE TR_GARANTIA
DROP PROCEDURE SP_I_TR_INSTRUMENTO
DROP PROCEDURE SP_U_TR_INSTRUMENTO
DROP PROCEDURE SP_D_TR_INSTRUMENTO
DROP PROCEDURE SP_S_TR_INSTRUMENTO
DROP PROCEDURE SP_I_TR_GARANTIA
DROP PROCEDURE SP_U_TR_GARANTIA
DROP PROCEDURE SP_D_TR_GARANTIA
DROP PROCEDURE SP_S_TR_GARANTIA


--Tabela de Instrumentos
CREATE TABLE TR_INSTRUMENTO(
INSTRUMENTO_IN_ID INT NOT NULL IDENTITY CONSTRAINT TR_PK_INSTRUMENTO PRIMARY KEY,
INSTRUMENTO_ST_NOME VARCHAR(50) NOT NULL,
INSTRUMENTO_ST_FAMILIA VARCHAR(50) NOT NULL,
INSTRUMENTO_ST_TAMANHO VARCHAR(50) NOT NULL DEFAULT 'Médio',
INSTRUMENTO_ST_QUALIDADE VARCHAR(50) NOT NULL,
INSTRUMENTO_RE_PRECO NUMERIC(8,2) NOT NULL CONSTRAINT TR_CK_INSTRUMENTO CHECK (INSTRUMENTO_RE_PRECO >=0)
);

--Tabela de Garantia
CREATE TABLE TR_GARANTIA(
GARANTIA_IN_CODIGO INT NOT NULL IDENTITY CONSTRAINT TR_PK_GARANTIA PRIMARY KEY,
GARANTIA_ST_CAUSA VARCHAR(300) NOT NULL,
GARANTIA_ST_REPARO VARCHAR(400) NOT NULL,
INSTRUMENTO_IN_ID INT NOT NULL UNIQUE CONSTRAINT TR_FK_GARANTIA_INSTRUMENTO FOREIGN KEY REFERENCES TR_INSTRUMENTO(INSTRUMENTO_IN_ID)
);


INSERT INTO TR_INSTRUMENTO(INSTRUMENTO_ST_NOME, INSTRUMENTO_ST_FAMILIA, INSTRUMENTO_ST_TAMANHO, INSTRUMENTO_ST_QUALIDADE, INSTRUMENTO_RE_PRECO) 
VALUES('Violino', 'Cordas', 'Pequeno', 'Novo', '2000')
INSERT INTO TR_INSTRUMENTO(INSTRUMENTO_ST_NOME, INSTRUMENTO_ST_FAMILIA, INSTRUMENTO_ST_TAMANHO, INSTRUMENTO_ST_QUALIDADE, INSTRUMENTO_RE_PRECO) 
VALUES('Violoncelo', 'Cordas', 'Grande', 'Novo', '3000')
INSERT INTO TR_INSTRUMENTO(INSTRUMENTO_ST_NOME, INSTRUMENTO_ST_FAMILIA, INSTRUMENTO_ST_TAMANHO, INSTRUMENTO_ST_QUALIDADE, INSTRUMENTO_RE_PRECO) 
VALUES('Tuba', 'Metais', 'Grande', 'Novo', '15000')

--SaxBarítono é um exemplo de Default, pois possui o tamanho no padrão médio.
INSERT INTO TR_INSTRUMENTO(INSTRUMENTO_ST_NOME, INSTRUMENTO_ST_FAMILIA, INSTRUMENTO_ST_QUALIDADE, INSTRUMENTO_RE_PRECO) 
VALUES('SaxBarítono', 'Palhetas', 'Novo', '12000')

INSERT INTO TR_INSTRUMENTO(INSTRUMENTO_ST_NOME, INSTRUMENTO_ST_FAMILIA, INSTRUMENTO_ST_TAMANHO, INSTRUMENTO_ST_QUALIDADE, INSTRUMENTO_RE_PRECO) 
VALUES('Flauta Transversal', 'Madeiras', 'Pequeno', 'Novo', '5000')
INSERT INTO TR_INSTRUMENTO(INSTRUMENTO_ST_NOME, INSTRUMENTO_ST_FAMILIA, INSTRUMENTO_ST_TAMANHO, INSTRUMENTO_ST_QUALIDADE, INSTRUMENTO_RE_PRECO) 
VALUES('Violino', 'Cordas', 'Pequeno', 'Usado', '900')
INSERT INTO TR_INSTRUMENTO(INSTRUMENTO_ST_NOME, INSTRUMENTO_ST_FAMILIA, INSTRUMENTO_ST_TAMANHO, INSTRUMENTO_ST_QUALIDADE, INSTRUMENTO_RE_PRECO) 
VALUES('Trompete', 'Metais', 'Pequeno', 'Usado', '1200')

--Trombone é um exemplo de check constraint no valor do preço
INSERT INTO TR_INSTRUMENTO(INSTRUMENTO_ST_NOME, INSTRUMENTO_ST_FAMILIA, INSTRUMENTO_ST_QUALIDADE, INSTRUMENTO_RE_PRECO)
VALUES('Trombone', 'Metais', 'Novo', '1500')


INSERT INTO TR_GARANTIA(GARANTIA_ST_CAUSA, GARANTIA_ST_REPARO, INSTRUMENTO_IN_ID) 
VALUES('Instrumento caiu no chão.', 'Não reparado pois não atende os requisitos da garantia.', '1')
INSERT INTO TR_GARANTIA(GARANTIA_ST_CAUSA, GARANTIA_ST_REPARO, INSTRUMENTO_IN_ID) 
VALUES('Instrumento teve problema no pisto onde o mesmo não sobe depois de ser presionado.', 'Reparado pois atende os requisitos da garantia', '3')


SELECT * FROM TR_INSTRUMENTO
SELECT * FROM TR_GARANTIA
SELECT * FROM TR_GARANTIA AS GAR, TR_INSTRUMENTO AS INS WHERE GAR.INSTRUMENTO_IN_ID = INS.INSTRUMENTO_IN_ID



--Procedures da Tabela TR_INSTRUMENTO
--Procedure de Inclusão
CREATE PROCEDURE SP_I_TR_INSTRUMENTO(@nome VARCHAR(50), @familia VARCHAR(50), @qualidade VARCHAR(50), @preco NUMERIC(8,2))
AS
SET NOCOUNT ON
IF LEN(@nome) = 0 OR LEN(@familia) = 0 OR LEN(@qualidade) = 0 OR LEN(@preco) = 0
	BEGIN
		RAISERROR('Os parâmetros Nome, Familia, Qualidade e Preço são obrigatórios!!!',15,1)
	END
ELSE 
	BEGIN
		INSERT INTO TR_INSTRUMENTO(INSTRUMENTO_ST_NOME, INSTRUMENTO_ST_FAMILIA, INSTRUMENTO_ST_QUALIDADE, INSTRUMENTO_RE_PRECO)
		VALUES(@nome, @familia, @qualidade, @preco)
	END
RETURN
GO

EXEC SP_I_TR_INSTRUMENTO 'VIOLONCELO', '', '', '0'

EXEC SP_I_TR_INSTRUMENTO 'Violino', 'Cordas', 'Novo', '500'
EXEC SP_I_TR_INSTRUMENTO 'Acordeão', 'Não Definido', 'Novo', '8000'
EXEC SP_I_TR_INSTRUMENTO 'Clarinete', 'Madeiras', 'Novo', '7000'

--Procedure Alteração
CREATE PROCEDURE SP_U_TR_INSTRUMENTO(@nome VARCHAR(50), @familia VARCHAR(50), @tamanho VARCHAR(50), @qualidade VARCHAR(50), @preco NUMERIC(8,2), @ID INT)
AS
SET NOCOUNT ON
IF LEN(@nome) = 0 OR LEN(@familia) = 0 OR LEN(@tamanho) = 0 OR LEN(@qualidade) = 0 OR LEN(@preco) = 0
	BEGIN
		RAISERROR('Os parâmetros Nome, Familia, Tamanho, Qualidade e Preço são obrigatórios!!!',15,1)
	END
ELSE 
	BEGIN
		UPDATE TR_INSTRUMENTO 
		SET INSTRUMENTO_ST_NOME = @nome, 
			INSTRUMENTO_ST_FAMILIA = @familia, 
			INSTRUMENTO_ST_TAMANHO = @tamanho, 
			INSTRUMENTO_ST_QUALIDADE = @qualidade, 
			INSTRUMENTO_RE_PRECO = @preco 
		WHERE INSTRUMENTO_IN_ID = @ID
	END
RETURN
GO

EXEC SP_U_TR_INSTRUMENTO 'Violino', '', '', '', '0', '9'

EXEC SP_U_TR_INSTRUMENTO 'Violino', 'Cordas', 'Pequeno', 'Novo', '1200', '10'
EXEC SP_U_TR_INSTRUMENTO 'Viola', 'Cordas', 'Médio', 'Novo', '1200', '6'

--Procedure de Deleção
CREATE PROCEDURE SP_D_TR_INSTRUMENTO(@ID INT)
AS
SET NOCOUNT ON
IF @ID <= 0 
	BEGIN
		RAISERROR('O parâmetro ID necessita ser igual ou maior que Um',15,1)
	END
ELSE 
	BEGIN
		DELETE FROM TR_INSTRUMENTO
		WHERE INSTRUMENTO_IN_ID = @ID
	END
RETURN
GO

EXEC SP_D_TR_INSTRUMENTO ''

EXEC SP_D_TR_INSTRUMENTO '10'

--Procedure de Consulta
CREATE PROCEDURE SP_S_TR_INSTRUMENTO(@ID INT)
AS
SET NOCOUNT ON
IF @ID <= 0
	BEGIN
		RAISERROR('O parâmetro ID necessita ser igual ou maior que Um',15,1)
	END
ELSE 
	BEGIN
		SELECT * FROM TR_INSTRUMENTO WHERE INSTRUMENTO_IN_ID = @ID
	END
RETURN
GO

EXEC SP_S_TR_INSTRUMENTO ''
EXEC SP_S_TR_INSTRUMENTO '0'

EXEC SP_S_TR_INSTRUMENTO '7'
EXEC SP_S_TR_INSTRUMENTO '8'


--Procedures da Tabela TR_GARANTIA
--Procedure de Inclusão
CREATE PROCEDURE SP_I_TR_GARANTIA(@causa VARCHAR(300), @reparo VARCHAR(400), @ID INT)
AS
SET NOCOUNT ON
IF LEN(@causa) = 0 OR LEN(@reparo) = 0 OR LEN(@ID) = 0
	BEGIN
		RAISERROR('Os parâmetros Causa, Reparo e ID são obrigatórios!!!',15,1)
	END
ELSE
	BEGIN
		INSERT INTO TR_GARANTIA(GARANTIA_ST_CAUSA, GARANTIA_ST_REPARO, INSTRUMENTO_IN_ID)
		VALUES(@causa, @reparo, @ID)
	END
RETURN
GO

EXEC SP_I_TR_GARANTIA '', '', ''

EXEC SP_I_TR_GARANTIA 'Queda no chão', 'Não reparado pois não atende os requisitos da garantia', '8'
EXEC SP_I_TR_GARANTIA 'Queda no chão', 'Não reparado pois não atende os requisitos da garantia', '5'
EXEC SP_I_TR_GARANTIA 'Queda no chão', 'Não reparado pois não atende os requisitos da garantia', '2'

--Procedure Alteração
CREATE PROCEDURE SP_U_TR_GARANTIA(@causa VARCHAR(300), @reparo VARCHAR(400), @codigo INT)
AS
SET NOCOUNT ON
IF LEN(@causa) = 0 OR LEN(@reparo) = 0 OR LEN(@codigo) = 0
	BEGIN
		RAISERROR('Os parâmetros Causa, Reparo e Código são obrigatórios!!!',15,1)
	END
ELSE
	BEGIN
		UPDATE TR_GARANTIA
		SET GARANTIA_ST_CAUSA = @causa,
			GARANTIA_ST_REPARO = @reparo
		WHERE GARANTIA_IN_CODIGO = @codigo
	END
RETURN
GO

EXEC SP_U_TR_GARANTIA '', '', ''

EXEC SP_U_TR_GARANTIA 'Criança quebrou o produto', 'Não reparado pois não atende os requisitos da garantia', '5'
EXEC SP_U_TR_GARANTIA 'Adulto sentou em cima do instrumento', 'Não reparado pois não atende os requisitos da garantia', '4'

--Procedure Deleção
CREATE PROCEDURE SP_D_TR_GARANTIA(@codigo INT)
AS
SET NOCOUNT ON
IF @codigo <= 0 
	BEGIN
		RAISERROR('O parâmetro ID necessita ser igual ou maior que Um',15,1)
	END
ELSE 
	BEGIN
		DELETE FROM TR_GARANTIA
		WHERE GARANTIA_IN_CODIGO = @codigo
	END
RETURN
GO

EXEC SP_D_TR_GARANTIA ''

EXEC SP_D_TR_GARANTIA '2'

--Procedure de Consulta
CREATE PROCEDURE SP_S_TR_GARANTIA(@codigo INT)
AS
SET NOCOUNT ON
IF @codigo <= 0
	BEGIN
		RAISERROR('O parâmetro ID necessita ser igual ou maior que Um',15,1)
	END
ELSE 
	BEGIN
		SELECT * FROM TR_GARANTIA WHERE GARANTIA_IN_CODIGO = @codigo
	END
RETURN
GO

EXEC SP_S_TR_GARANTIA ''
EXEC SP_S_TR_GARANTIA '0'

EXEC SP_S_TR_GARANTIA '1'
EXEC SP_S_TR_GARANTIA '3'
